version: "1"
rules:
  - base: nixos-unstable
    upstream: NixOS:nixos-unstable
    mergeMethod: rebase
    assignees:
      - nyanloutre
    reviewers:
      - nyanloutre
  - base: nixos-19.09
    upstream: NixOS:nixos-19.09
    mergeMethod: rebase
    assignees:
      - nyanloutre
    reviewers:
      - nyanloutre
