name: Rebase on upstream

on:
  schedule:
    - cron: '* * * * *'

jobs:
  nixos-19_09:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: nixos-19.09
        fetch-depth: 0
    - name: Rebase and push
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag backups/nixos-19.09@$(date +%s)
        git push --tags
        git remote add upstream https://github.com/NixOS/nixpkgs.git
        git fetch upstream
        git rebase upstream/nixos-19.09
        git push --force
  nixos-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: nixos-unstable
        fetch-depth: 0
    - name: Rebase and push
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag backups/nixos-unstable@$(date +%s)
        git push --tags
        git remote add upstream https://github.com/NixOS/nixpkgs.git
        git fetch upstream
        git rebase upstream/nixos-unstable
        git push --force
