name: Rebase nixpkgs on upstream channels

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  nixos-rebase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [nixos-unstable, nixos-19.09]
    steps:
    - name: Checkout NixOS ${{ matrix.channel }} fork
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.channel }}
        fetch-depth: 0
    - name: Rebase and push
      env:
        NIXOS_CHANNEL: ${{ matrix.channel }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag backups/${NIXOS_CHANNEL}@$(date +%s)
        git push --tags
        git remote add upstream https://github.com/NixOS/nixpkgs.git
        git fetch upstream
        git rebase upstream/${NIXOS_CHANNEL}
        git push --force
